version: '3.9'
services:
  api_core:
    restart: always
    context: ./api_core
    build: .
    ports:
      - 4003:4003
    volumes:
      - .:/api_core
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
